kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arena-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-arena-acl/amt-arena-acl:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  env:
    - name: AMT_ARENA_ORDS_PROXY_SCOPE
      value: api://dev-fss.amt.amt-arena-ords-proxy/.default
    - name: AMT_ARENA_ORDS_PROXY_URL
      value: https://amt-arena-ords-proxy.dev-fss-pub.nais.io
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://dev-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local
    - name: TOGGLE_HENT_GJENNOMFORING_FRA_MULIGHETSROMMET
      value: "true"

    # Kafka topics
    - name: AMT_TOPIC
      value: amt.amt-tiltak-v1
    - name: ARENA_TILTAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakendret-v1-q2
    - name: ARENA_TILTAKGJENNOMFORING_TOPIC
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-q2
    - name: ARENA_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-q2
    - name: ARENA_SAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakssakendret-v1-q2
  gcp:
    sqlInstances:
      - name: amt-arena-acl-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: amt-arena-acl
            envVarPrefix: DB
