kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arena-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/amt-arena-acl/amt-arena-acl:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: AMT_ARENA_ORDS_PROXY_SCOPE
      value: api://prod-fss.amt.amt-arena-ords-proxy/.default
    - name: POAO_GCP_PROXY_SCOPE
      value: api://prod-fss.pto.poao-gcp-proxy/.default
    - name: POAO_GCP_PROXY_URL
      value: https://poao-gcp-proxy.prod-fss-pub.nais.io
    # Kafka topics
    - name: AMT_TOPIC
      value: amt.amt-tiltak-v1
    - name: ARENA_TILTAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakendret-v1-p
    - name: ARENA_TILTAKGJENNOMFORING_TOPIC
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p
    - name: ARENA_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p
    - name: ARENA_SAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakssakendret-v1-p
  gcp:
    sqlInstances:
      - name: amt-arena-acl-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: amt-arena-acl
            envVarPrefix: DB
