kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-arena-acl
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 50
  liveness:
    path: /internal/health/liveness
    initialDelay: 50
    timeout: 3
  replicas:
    disableAutoScaling: true
    min: 0
    max: 0
  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: amt-tiltak
      external:
        - host: amt-arena-ords-proxy.prod-fss-pub.nais.io
        - host: amt-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: amt-aktivitetskort-publisher
  kafka:
    pool: nav-prod
  envFrom:
    - secret: amt-arena-acl-unleash-api-token
  env:
    - name: AMT_ARENA_ORDS_PROXY_SCOPE
      value: api://prod-fss.amt.amt-arena-ords-proxy/.default
    - name: AMT_ARENA_ORDS_PROXY_URL
      value: https://amt-arena-ords-proxy.prod-fss-pub.nais.io
    - name: MULIGHETSROMMET_API_SCOPE
      value: api://prod-gcp.team-mulighetsrommet.mulighetsrommet-api/.default
    - name: MULIGHETSROMMET_API_URL
      value: http://mulighetsrommet-api.team-mulighetsrommet.svc.cluster.local
    - name: AMTTILTAK_SCOPE
      value: api://prod-gcp.amt.amt-tiltak/.default
    - name: AMTTILTAK_URL
      value: http://amt-tiltak

    # Kafka topics
    - name: AMT_TOPIC
      value: amt.amt-tiltak-v1
    - name: ARENA_TILTAKGJENNOMFORING_TOPIC
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p
    - name: ARENA_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p
    - name: ARENA_HIST_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-histtiltakdeltakerendret-v1-p

  gcp:
    sqlInstances:
      - name: amt-arena-acl-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: amt-arena-acl
            envVarPrefix: DB

  observability:
      autoInstrumentation:
        enabled: true
        runtime: java
      logging:
        destinations:
          - id: elastic
          - id: loki
