package no.nav.amt.arena.acl.utils

const val ARENA_TILTAK_TABLE_NAME = "SIAMO.TILTAK"
const val ARENA_GJENNOMFORING_TABLE_NAME = "SIAMO.TILTAKGJENNOMFORING"
const val ARENA_DELTAKER_TABLE_NAME = "SIAMO.TILTAKDELTAKER"
const val ARENA_SAK_TABLE_NAME = "SIAMO.SAK"

const val ONE_MINUTE = 60 * 1000L
const val ONE_HOUR = 60 * 60 * 1000L
const val AT_MIDNIGHT = "0 0 0 * * *"
