package no.nav.amt.arena.acl.utils

const val ARENA_GJENNOMFORING_TABLE_NAME = "SIAMO.TILTAKGJENNOMFORING"
const val ARENA_DELTAKER_TABLE_NAME = "SIAMO.TILTAKDELTAKER"
const val ARENA_HIST_DELTAKER_TABLE_NAME = "SIAMO.HIST_TILTAKDELTAKER"

const val ONE_MINUTE = 60 * 1000L
const val FIVE_MINUTES = ONE_MINUTE * 5
const val TEN_MINUTES = ONE_MINUTE * 10
const val ONE_HOUR = 60 * 60 * 1000L
const val AT_MIDNIGHT = "0 0 0 * * *"
