{
 "title": "Ingest Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "New Tiltak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAK\", status=\"NEW\"}"
    }
   ]
  },
  {
   "title": "Handled Tiltak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAK\", status=\"HANDLED\"}"
    }
   ]
  },
  {
   "title": "Retry Tiltak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAK\", status=\"RETRY\"}"
    }
   ]
  },
  {
   "title": "Failed Tiltak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAK\", status=\"FAILED\"}"
    }
   ]
  },
  {
   "title": "Ignored Tiltak",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAK\", status=\"IGNORED\"}"
    }
   ]
  },
  {
   "title": "New Gjennomføringer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAKGJENNOMFORING\", status=\"NEW\"}"
    }
   ]
  },
  {
   "title": "Handled Gjennomføringer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAKGJENNOMFORING\", status=\"HANDLED\"}"
    }
   ]
  },
  {
   "title": "Retry Gjennomføringer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAKGJENNOMFORING\", status=\"RETRY\"}"
    }
   ]
  },
  {
   "title": "Ignored Gjennomføringer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amt_arena_acl_ingest_status{table=\"SIAMO.TILTAKGJENNOMFORING\", status=\"IGNORED\"}"
    }
   ]
  }
 ]
}