package no.nav.amt.arena.acl.clients.amttiltak

enum class DeltakerStatusDto {
	UTKAST_TIL_PAMELDING, AVBRUTT_UTKAST,
	VENTER_PA_OPPSTART, DELTAR, HAR_SLUTTET, FULLFORT, IKKE_AKTUELL, FEILREGISTRERT,
	SOKT_INN, VURDERES, VENTELISTE, AVBRUTT, PABEGYNT_REGISTRERING
}
