name: Deploy application
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/amt-arena-acl/actions/workflows/deploy.yaml
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

env:
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    permissions:
      contents: "write"
      id-token: "write"
      security-events: "write"
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build artifacts
        run: ./gradlew build --console=plain --no-daemon

      - name: Dependency submission (for Dependabot)
        uses: gradle/actions/dependency-submission@v4

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        env: # Workaround for rate limiting inntil denne er fikset: https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        with:
          team: amt
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}


  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.test-build-and-push.outputs.telemetry }}

  deploy-prod:
    name: Deploy application to production
    needs: [ test-build-and-push, deploy-dev ]
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
          TELEMETRY: ${{ needs.test-build-and-push.outputs.telemetry }}
