name: Run tests
on:
  push:
    branches-ignore:
      - main
jobs:
  sonar:
    uses: navikt/sif-gha-workflows/.github/workflows/gradle-sonar.yml@main
    permissions:
      contents: read
      pull-requests: read
    secrets: inherit
    with:
      readertoken: false
      javaversion: 21

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew check --console=plain --no-daemon
